name: api-gateway-test
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: 도커 로그인
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 도커 이미지 빌드와 푸시
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/bookstore-service-test:latest .
          docker push ghcr.io/${{ github.repository_owner }}/bookstore-service-test:latest
          echo "빌드완료"

      - name: 서버 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          GH_TOKEN: ${{ secrets.NEW_TOKEN }}
          GH_OWNER: ${{ github.repository_owner }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          host: s2.java21.net
          username: be12-team4
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 8822
          envs: GH_TOKEN,GH_OWNER,SSH_PRIVATE_KEY
          script_stop: true
          script: |
            echo $GH_TOKEN | docker login ghcr.io -u baejongto --password-stdin
            cd ~
            docker compose stop bookstore-service || true
            docker compose rm -f bookstore-service || true
            docker compose pull bookstore-service
            docker compose up -d bookstore-service
#            docker stop api-gateway-test || true
#            docker rm api-gateway-test || true
#            docker pull ghcr.io/$GH_OWNER/api-gateway-test:latest
#            docker run -d --name api-gateway-test -p 10463:10463 \
#            ghcr.io/$GH_OWNER/api-gateway-test:latest
